using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyTitleAttribute("JPEGator.dll")]
[assembly: AssemblyDescriptionAttribute(".NET Compact Framework wrapper for the Independent JPEG Group\'s software")]
[assembly: AssemblyProductAttribute("JPEGator")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2005-2009, Aleh Dzenisiuk")]
[assembly: AssemblyVersionAttribute("1.6.1549.0")]

